### PR TITLE
fixed related_by_category finder to exclude target obj and fixed url che...

### PR DESCRIPTION
**Pull request by MichalMaM**
fixed related_by_category finder to exclude target obj and fixed url check for non static publishables in clean method of publishable

### CODE REVIEW

**Comment by honzakral** [comment]
Please never include white-space and style fixes in unrelated pieces of code it makes the patch very unreadable.

Also do you have a use-case for replacinf self.**class** and self with Publishable? Do you realize that your change means that users will get a confuxing message? ("publishable" instead of "article")

I will revert this commit, it's bad and commits like this should never make it to ella, if you care about it, submit separate tickets for all the changes you made with sufficient reasoning

**Comment by MichalMaM** [comment]
Sorry for white-space and style fixes in same commit (usually when I see it in my IDE I correct it during work...). But I think that is not good idea to revert this commit becouse this code is correct and really repair bugs in ella (I hope that it is readable from tests). Firstly Publishable should replace self.**class**, becouse self.**class** validate url unique for specific content type (for example only in articles query set) and not for all publishables (try to add test from this commit to current ella and you see it) and it breaks unique url per publishable. Second fix in commit is for category related finder. Example in current version of ella: I have publishble x and x has set category y and is also listed this category and I want 4 related objects by category and finder gives me only 3 objects although there is many objects (This situation happens only if position of x in listing qs is less than count specification). Sometimes I love these boundary conditions :). Finally I can split this commit to three commits (publishable url validation, category related finder, white-space and style fixes), but the only thing that changes is a little better readability commits and I do not know if it's worth it.

**Comment by honzakral** [comment]
If `self.__class__ validate` doesn't do the right thing, then IT should be fixed, not just circumvented; let alone as undocummented part of completely unrelated commit!

I am not aying that the code is wrong, I am saying that the commit is wrong, the solution is to post a correct commit or wait till I have time to do it myself.

**Comment by MichalMaM** [comment]
So I try to split to separate commits and during tomorrow send pull request again.

**Comment by honzakral** [comment]
thanks!

**Pull request merged**
