### PR TITLE
do not throw AttributeError in method show_title of positon admin

### PR DESCRIPTION
**Pull request by MichalMaM**
Do not throw AttributeError in method show_title of positon admin if target obj has not title attribute.

### CODE REVIEW

**Comment by honzakral** [comment]
please include tests in any PR

**Comment by MichalMaM** [comment]
done

**Comment by honzakral** [comment]
Thanks, I also changed the tests a bit to be more lightweight and avoid hitting the db altogether.

**Comment by MichalMaM** [comment]
Ok, thanks

**Pull request merged**
