### PR TITLE
changed RelatedInlineAdmin to more humane option

### PR DESCRIPTION
**Pull request by MichalMaM**

### CODE REVIEW

**Comment by honzakral** [comment]
You got this backwards - Related model is there to bind any object to a publishable - it's supposed to be at the publishable's page in the admin so regular Inline admin is desired.

**Comment by MichalMaM** [comment]
Ok, but current behavior of admin with combination of related template tag is confusing... Example: I add 3 related objects in publishable admin for publishable x and in detail template I use related template tag for this publishable (such as {% related 3 for x as related_list %}) and in the result is empty (if i use directly_related finder). But if I use related tag for one of 3 added objects the result is publishable x.

**Comment by honzakral** [comment]
that is a bug that should be fixed then. Fixing now

**Comment by honzakral** [comment]
fixed in https://github.com/ella/ella/commit/c100e0b8369173d21810d6df09ab9012aac5540e

**Comment by MichalMaM** [comment]
Nice, thanks (+1 for **eq** method on Publishable :))

**Pull request closed without merging**
